import * as PIXI from 'pixi.js';
import { Scrollbox } from 'pixi-scrollbox'
export const utils = PIXI.utils,
             Application = PIXI.Application,
             Container = PIXI.Container,
             loader = PIXI.Loader,
             ticker = PIXI.Ticker,
             resources = PIXI.resources,
             TextureCache = PIXI.utils.TextureCache,
             Sprite = PIXI.Sprite,
             filters = PIXI.filters,
             Graphics = PIXI.Graphics,
             Texture = PIXI.Texture,
             BaseTexture = PIXI.BaseTexture,
             AnimatedSprite = PIXI.AnimatedSprite,
             Text = PIXI.Text,
             TextStyle = PIXI.TextStyle,
             InteractionEvent = PIXI.InteractionEvent,
             SBox = Scrollbox,
             Rectangle = PIXI.Rectangle;
